<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [

            // ── BURGER (category_id = 1) ──────────────────────────
            [
                'category_id'      => 1,
                'name'             => 'Classic Burger',
                'slug'             => 'classic-burger',
                'description'      => 'Burger bò truyền thống với rau xà lách, cà chua, phô mai và sốt đặc trưng.',
                'base_price'       => 45000,
                'image'            => 'classic-burger.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bò', 'cổ điển', 'bestseller']),
                'prep_time_minutes' => 8,
            ],
            [
                'category_id'      => 1,
                'name'             => 'Double Smash',
                'slug'             => 'double-smash',
                'description'      => 'Hai lớp thịt bò smash mỏng giòn, phô mai tan chảy, dưa chuột muối.',
                'base_price'       => 65000,
                'image'            => 'double-smash.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bò', 'double', 'phô mai']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 1,
                'name'             => 'Crispy Chicken',
                'slug'             => 'crispy-chicken',
                'description'      => 'Gà phi lê chiên giòn, xà lách bắp cải, sốt mayo.',
                'base_price'       => 55000,
                'image'            => 'crispy-chicken.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'giòn']),
                'prep_time_minutes' => 9,
            ],
            [
                'category_id'      => 1,
                'name'             => 'Spicy Chicken',
                'slug'             => 'spicy-chicken',
                'description'      => 'Gà phi lê cay, jalapeño, sốt sriracha, rau diếp.',
                'base_price'       => 59000,
                'image'            => 'spicy-chicken.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'cay', 'spicy']),
                'prep_time_minutes' => 9,
            ],
            [
                'category_id'      => 1,
                'name'             => 'Mushroom Swiss',
                'slug'             => 'mushroom-swiss',
                'description'      => 'Thịt bò, nấm xào bơ, phô mai Swiss tan chảy.',
                'base_price'       => 62000,
                'image'            => 'mushroom-swiss.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bò', 'nấm', 'phô mai']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 1,
                'name'             => 'BBQ Bacon',
                'slug'             => 'bbq-bacon',
                'description'      => 'Thịt bò, bacon giòn, sốt BBQ đậm đà, hành caramel.',
                'base_price'       => 69000,
                'image'            => 'bbq-bacon.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bò', 'bacon', 'bbq', 'bestseller']),
                'prep_time_minutes' => 11,
            ],

            // ── PIZZA (category_id = 2) ───────────────────────────
            [
                'category_id'      => 2,
                'name'             => 'Pizza Phô Mai',
                'slug'             => 'pizza-pho-mai',
                'description'      => 'Đế mỏng giòn, sốt cà chua, 4 loại phô mai tan chảy.',
                'base_price'       => 89000,
                'image'            => 'pizza-pho-mai.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['phô mai', 'chay', 'bestseller']),
                'prep_time_minutes' => 15,
            ],
            [
                'category_id'      => 2,
                'name'             => 'Pizza BBQ Gà',
                'slug'             => 'pizza-bbq-ga',
                'description'      => 'Đế dày mềm, sốt BBQ, gà nướng, ớt chuông, hành tây.',
                'base_price'       => 99000,
                'image'            => 'pizza-bbq-ga.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'bbq']),
                'prep_time_minutes' => 15,
            ],
            [
                'category_id'      => 2,
                'name'             => 'Pizza Hải Sản',
                'slug'             => 'pizza-hai-san',
                'description'      => 'Tôm, mực, nghêu, sốt kem tỏi, phô mai mozzarella.',
                'base_price'       => 109000,
                'image'            => 'pizza-hai-san.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['hải sản', 'tôm', 'mực']),
                'prep_time_minutes' => 18,
            ],
            [
                'category_id'      => 2,
                'name'             => 'Pizza Cay Kiểu Ý',
                'slug'             => 'pizza-cay-kieu-y',
                'description'      => 'Xúc xích cay pepperoni, ớt, sốt cà chua đậm.',
                'base_price'       => 95000,
                'image'            => 'pizza-cay-kieu-y.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['cay', 'pepperoni', 'spicy']),
                'prep_time_minutes' => 15,
            ],

            // ── MỲ Ý (category_id = 3) ────────────────────────────
            [
                'category_id'      => 3,
                'name'             => 'Spaghetti Bò Bằm',
                'slug'             => 'spaghetti-bo-bam',
                'description'      => 'Spaghetti với sốt bolognese thịt bò bằm đậm đà, rắc phô mai parmesan.',
                'base_price'       => 75000,
                'image'            => 'spaghetti-bo-bam.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bò', 'sốt đỏ', 'pasta']),
                'prep_time_minutes' => 12,
            ],
            [
                'category_id'      => 3,
                'name'             => 'Spaghetti Kem Gà',
                'slug'             => 'spaghetti-kem-ga',
                'description'      => 'Spaghetti carbonara, gà xào kem, bacon, trứng.',
                'base_price'       => 79000,
                'image'            => 'spaghetti-kem-ga.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'kem', 'carbonara']),
                'prep_time_minutes' => 12,
            ],
            [
                'category_id'      => 3,
                'name'             => 'Penne Cà Chua',
                'slug'             => 'penne-ca-chua',
                'description'      => 'Penne sốt marinara cà chua tươi, rau basil, chay hoàn toàn.',
                'base_price'       => 69000,
                'image'            => 'penne-ca-chua.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['chay', 'cà chua', 'pasta']),
                'prep_time_minutes' => 10,
            ],

            // ── SANDWICH (category_id = 4) ────────────────────────
            [
                'category_id'      => 4,
                'name'             => 'Sandwich Gà Nướng',
                'slug'             => 'sandwich-ga-nuong',
                'description'      => 'Bánh mì sandwich, gà nướng thảo mộc, rau xà lách, cà chua.',
                'base_price'       => 49000,
                'image'            => 'sandwich-ga-nuong.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'nướng', 'lành mạnh']),
                'prep_time_minutes' => 8,
            ],
            [
                'category_id'      => 4,
                'name'             => 'Sandwich Trứng Phô Mai',
                'slug'             => 'sandwich-trung-pho-mai',
                'description'      => 'Trứng ốp la, phô mai cheddar, bánh mì nướng giòn.',
                'base_price'       => 45000,
                'image'            => 'sandwich-trung-pho-mai.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['trứng', 'phô mai', 'buổi sáng']),
                'prep_time_minutes' => 7,
            ],
            [
                'category_id'      => 4,
                'name'             => 'Sandwich BLT Bacon',
                'slug'             => 'sandwich-blt-bacon',
                'description'      => 'Bacon giòn, xà lách, cà chua, mayo, bánh mì trắng.',
                'base_price'       => 55000,
                'image'            => 'sandwich-blt-bacon.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['bacon', 'blt']),
                'prep_time_minutes' => 8,
            ],

            // ── GÀ CHIÊN (category_id = 5) ───────────────────────
            [
                'category_id'      => 5,
                'name'             => 'Gà Chiên Giòn (2 miếng)',
                'slug'             => 'ga-chien-gion-2',
                'description'      => 'Gà chiên giòn lớp vỏ đặc trưng, 2 miếng.',
                'base_price'       => 45000,
                'image'            => 'ga-chien-gion.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'giòn', 'chiên']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Gà Chiên Giòn (4 miếng)',
                'slug'             => 'ga-chien-gion-4',
                'description'      => 'Gà chiên giòn lớp vỏ đặc trưng, 4 miếng.',
                'base_price'       => 79000,
                'image'            => 'ga-chien-gion.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'giòn', 'chiên', 'phần lớn']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Gà Chiên Cay (2 miếng)',
                'slug'             => 'ga-chien-cay-2',
                'description'      => 'Gà chiên cay xé lưỡi, 2 miếng.',
                'base_price'       => 49000,
                'image'            => 'ga-chien-cay.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'cay', 'chiên', 'spicy']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Gà Chiên Cay (4 miếng)',
                'slug'             => 'ga-chien-cay-4',
                'description'      => 'Gà chiên cay xé lưỡi, 4 miếng.',
                'base_price'       => 85000,
                'image'            => 'ga-chien-cay.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'cay', 'chiên', 'spicy', 'phần lớn']),
                'prep_time_minutes' => 10,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Cánh Gà Mắm Tỏi',
                'slug'             => 'canh-ga-mam-toi',
                'description'      => 'Cánh gà chiên giòn sốt mắm tỏi đặc trưng Việt Nam.',
                'base_price'       => 59000,
                'image'            => 'canh-ga-mam-toi.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'mắm tỏi', 'bestseller']),
                'prep_time_minutes' => 12,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Đùi Gà Chiên Giòn',
                'slug'             => 'dui-ga-chien-gion',
                'description'      => 'Đùi gà nguyên chiếc, vỏ giòn, thịt mềm thơm.',
                'base_price'       => 55000,
                'image'            => 'dui-ga-chien-gion.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'đùi', 'giòn']),
                'prep_time_minutes' => 12,
            ],
            [
                'category_id'      => 5,
                'name'             => 'Gà Popcorn',
                'slug'             => 'ga-popcorn',
                'description'      => 'Miếng gà nhỏ chiên giòn cỡ một miếng, ăn vặt tuyệt vời.',
                'base_price'       => 39000,
                'image'            => 'ga-popcorn.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'snack', 'ăn vặt']),
                'prep_time_minutes' => 8,
            ],

            // ── SIDES (category_id = 6) ───────────────────────────
            [
                'category_id'      => 6,
                'name'             => 'Khoai Tây Chiên (Nhỏ)',
                'slug'             => 'khoai-tay-nho',
                'description'      => 'Khoai tây cắt sợi chiên vàng giòn, size nhỏ.',
                'base_price'       => 19000,
                'image'            => 'khoai-tay-chien.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['khoai', 'chiên', 'sides']),
                'prep_time_minutes' => 5,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Khoai Tây Chiên (Vừa)',
                'slug'             => 'khoai-tay-vua',
                'description'      => 'Khoai tây cắt sợi chiên vàng giòn, size vừa.',
                'base_price'       => 25000,
                'image'            => 'khoai-tay-chien.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['khoai', 'chiên', 'sides']),
                'prep_time_minutes' => 5,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Khoai Tây Chiên (Lớn)',
                'slug'             => 'khoai-tay-lon',
                'description'      => 'Khoai tây cắt sợi chiên vàng giòn, size lớn.',
                'base_price'       => 32000,
                'image'            => 'khoai-tay-chien.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['khoai', 'chiên', 'sides', 'phần lớn']),
                'prep_time_minutes' => 5,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Onion Rings',
                'slug'             => 'onion-rings',
                'description'      => 'Vòng hành tây tẩm bột chiên giòn, chấm sốt.',
                'base_price'       => 29000,
                'image'            => 'onion-rings.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['hành', 'chiên', 'sides']),
                'prep_time_minutes' => 6,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Nuggets Gà (6 miếng)',
                'slug'             => 'nuggets-6',
                'description'      => 'Miếng gà nugget chiên giòn, 6 miếng, kèm sốt chấm.',
                'base_price'       => 29000,
                'image'            => 'nuggets.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'nuggets', 'sides']),
                'prep_time_minutes' => 7,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Nuggets Gà (12 miếng)',
                'slug'             => 'nuggets-12',
                'description'      => 'Miếng gà nugget chiên giòn, 12 miếng, kèm sốt chấm.',
                'base_price'       => 49000,
                'image'            => 'nuggets.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['gà', 'nuggets', 'sides', 'phần lớn']),
                'prep_time_minutes' => 7,
            ],
            [
                'category_id'      => 6,
                'name'             => 'Coleslaw',
                'slug'             => 'coleslaw',
                'description'      => 'Salad bắp cải, cà rốt trộn sốt kem nhẹ.',
                'base_price'       => 15000,
                'image'            => 'coleslaw.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['salad', 'chay', 'sides', 'lành mạnh']),
                'prep_time_minutes' => 3,
            ],

            // ── ĐỒ UỐNG (category_id = 7) ────────────────────────
            [
                'category_id'      => 7,
                'name'             => 'Nước Ngọt',
                'slug'             => 'nuoc-ngot',
                'description'      => 'Coca-Cola / Pepsi / Sprite — ghi chú loại khi đặt.',
                'base_price'       => 15000,
                'image'            => 'nuoc-ngot.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['nước', 'có ga', 'ngọt']),
                'prep_time_minutes' => 1,
            ],
            [
                'category_id'      => 7,
                'name'             => 'Trà Chanh',
                'slug'             => 'tra-chanh',
                'description'      => 'Trà xanh pha chanh tươi, đá lạnh.',
                'base_price'       => 19000,
                'image'            => 'tra-chanh.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['trà', 'chanh', 'mát']),
                'prep_time_minutes' => 2,
            ],
            [
                'category_id'      => 7,
                'name'             => 'Sữa Lắc Vani',
                'slug'             => 'sua-lac-vani',
                'description'      => 'Sữa lắc hương vani đậm creamy.',
                'base_price'       => 35000,
                'image'            => 'sua-lac.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['sữa lắc', 'ngọt', 'vani']),
                'prep_time_minutes' => 3,
            ],
            [
                'category_id'      => 7,
                'name'             => 'Sữa Lắc Dâu',
                'slug'             => 'sua-lac-dau',
                'description'      => 'Sữa lắc hương dâu tây tươi.',
                'base_price'       => 35000,
                'image'            => 'sua-lac.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['sữa lắc', 'ngọt', 'dâu']),
                'prep_time_minutes' => 3,
            ],
            [
                'category_id'      => 7,
                'name'             => 'Sữa Lắc Chocolate',
                'slug'             => 'sua-lac-chocolate',
                'description'      => 'Sữa lắc chocolate đậm vị.',
                'base_price'       => 35000,
                'image'            => 'sua-lac.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['sữa lắc', 'ngọt', 'chocolate']),
                'prep_time_minutes' => 3,
            ],
            [
                'category_id'      => 7,
                'name'             => 'Nước Suối',
                'slug'             => 'nuoc-suoi',
                'description'      => 'Nước suối đóng chai 500ml.',
                'base_price'       => 10000,
                'image'            => 'nuoc-suoi.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['nước', 'không đường']),
                'prep_time_minutes' => 1,
            ],

            // ── COMBO (category_id = 8) ───────────────────────────
            [
                'category_id'      => 8,
                'name'             => 'Combo Cơ Bản',
                'slug'             => 'combo-co-ban',
                'description'      => '1 Classic Burger + Khoai tây chiên nhỏ + Nước ngọt. Tiết kiệm hơn gọi lẻ.',
                'base_price'       => 69000,
                'image'            => 'combo-co-ban.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['combo', 'tiết kiệm', '1 người']),
                'prep_time_minutes' => 12,
            ],
            [
                'category_id'      => 8,
                'name'             => 'Combo Đôi',
                'slug'             => 'combo-doi',
                'description'      => '2 Burger + Khoai tây chiên lớn + 2 Nước ngọt. Dành cho 2 người.',
                'base_price'       => 149000,
                'image'            => 'combo-doi.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['combo', 'tiết kiệm', '2 người']),
                'prep_time_minutes' => 15,
            ],
            [
                'category_id'      => 8,
                'name'             => 'Combo Gia Đình',
                'slug'             => 'combo-gia-dinh',
                'description'      => '4 Burger + 2 Khoai tây chiên lớn + 4 Nước ngọt. Dành cho cả nhà.',
                'base_price'       => 279000,
                'image'            => 'combo-gia-dinh.jpg',
                'is_available'     => 1,
                'tags'             => json_encode(['combo', 'tiết kiệm', 'gia đình', '4 người']),
                'prep_time_minutes' => 20,
            ],
        ];

        foreach ($items as $item) {
            MenuItem::create($item);
        }
    }
}
